# Core application configuration
server.port: 8051
spring.application.name: Projects

# Cloud configuration
eureka.client.enabled: false
spring.cloud.hypermedia.refresh.initial-delay: 100
spring.cloud.hypermedia.refresh.fixed-delay: 500

# Logging
logging.level.org.springframework.cloud.client.hypermedia: DEBUG

spring:
    jpa:
        #Set to true to show generated queries
        show-sql: true
        hibernate:
            ddl-auto: create
        database: HSQL
        properties.hibernate:
            default-schema: PUBLIC
            dialect: org.hibernate.dialect.HSQLDialect
    datasource:
        initialization-mode: never
        jdbc-url: jdbc:hsqldb:mem:test;INIT=create schema IF NOT EXISTS mydb;DB_CLOSE_DELAY=-1
        username: sa
        password:
        driver-class-name: org.hsqldb.jdbcDriver
    data.rest.default-page-size: 25
