create table project (id integer generated by default as identity (start with 1), extId varchar(255), name varchar(255), projectType varchar(255), source integer, status varchar(255), parent_id integer, ticket_id integer, primary key (id));
create table ticket (id integer generated by default as identity (start with 1), extId varchar(255), problemSummary varchar(255), source integer not null, primary key (id));
alter table project add constraint FKt0just6g3205u402vn88i0fhy foreign key (parent_id) references project;
alter table project add constraint FKltdec9iox34yj9rxw81uwbpgp foreign key (ticket_id) references ticket;

INSERT INTO ticket (extId, source, problemSummary) VALUES ('03764542', 1, 'The router broke again');
INSERT INTO project (extId, source, projectType, name, status, parent_id, ticket_id) VALUES ('PRJ012345', 1, 'Deployment', 'Setup services at location 1234', 'Open', null, null);
INSERT INTO project (extId, source, projectType, name, status, parent_id, ticket_id) VALUES ('PRJ012346', 1, 'Deployment', 'Install broadband service at location 1234', 'Open', 1, null);
INSERT INTO project (extId, source, projectType, name, status, parent_id, ticket_id) VALUES ('PRJ012347', 1, 'Repair', 'Repair broadband service at location 1234', 'Open', null, 1);
